title: Make a difference
hero_image: images/banner.png
description: make-a-difference description
version: 4
listed: false
copyedit: false
last_tested: "2020-09-14"
steps:
  - title: Introduction
  - title: Get inspiration
  - title: How to  ...
  - title: Choose your theme
  - title: Make a sprite move
  - title: Adapting a sprite's appearence
  - title: User interaction
  - title: Adding more sprites
  - title: Share
  - title: Reflect
  - title: What next?
