title: Interactive Animation
hero_image: images/banner.png
description: Create a project -  relaxing, energising, funny, inspiring - to try and change someone’s mood using sprites that move over a backdrop
version: 4
listed: false
copyedit: false
last_tested: "2020-09-14"
steps:
  - title: Introduction
  - title: Get inspiration
  - title: Choose your theme
  - title: Animate using motion
  - title: Change the look of your sprite
  - title: Animate using looks
  - title: Do something when clicked
  - title: Add more sprites
  - title: Share
  - title: Reflect
  - title: What next?
